### ISSUE TITLE
Support exporting to SARIF reports

### ISSUE THREAD

**Issue by ligurio** [ispras/casr#105]
The Static Analysis Results Interchange Format (SARIF) [^1][^2][^3] is an industry standard format for the output of static analysis tools. Many code scanning tools support exporting to SARIF: CodeQL [^4], PVS Studio [^5], semgrep [^6].

GitHub (and probably other platforms like Gitlab) allows importing SARIF report and show warnings in SARIF report as annotations in pull requests. It is quire convenient for PR authors: you don't need to scan text logs by eye, warnings reported as a review comment and annotations is attached to a code that triggered a warning, so you see context and warning together.

With code scanning tools/linters it is possible to make PR annotations using reviewdog, see a list of tools supported by reviewdog [^7].

I believe it would be useful for casr users to have an ability to export reports to SARIF format or something other that allows making PR annotations in Github.

[^1]: https://sarifweb.azurewebsites.net/
[^2]: https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=sarif
[^3]: https://github.com/oasis-tcs/sarif-spec
[^4]: https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/sarif-output
[^5]: https://pvs-studio.com/en/docs/manual/6590/
[^6]: https://semgrep.dev/docs/cli-reference/
[^7]: https://github.com/reviewdog/reviewdog#public-reviewdog-github-actions

**Comment by SweetVishnya** [comment]
Awesome idea! One more link from me:

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning
