### ISSUE TITLE
Support for additional fuzzing testing tools

### ISSUE THREAD

**Issue by keller05** [ispras/casr#118]
It will be useful to collect crash reports from:

- [syzkaller](https://github.com/google/syzkaller)
- [jsfuzz](https://github.com/fuzzitdev/jsfuzz)

**Comment by SweetVishnya** [comment]
Yeah, it would be nice to support those. However, I suppose maintainers team won't have time for this in near future. External pull requests are always welcomed!)

**Comment by SweetVishnya** [comment]
I created a separate issue #122 for jsfuzz as it seems that it can be supported easier and faster.

**Comment by mimicria** [comment]
@SweetVishnya а есть шанс, что будет поддержка [honggfuzz](https://github.com/google/honggfuzz) ?

**Comment by SweetVishnya** [comment]
> @SweetVishnya а есть шанс, что будет поддержка [honggfuzz](https://github.com/google/honggfuzz) ?

А можно пример того, как выглядит выходная директория и строчка запуска Honggfuzz? Желательно в параллельном режиме.

**Comment by SweetVishnya** [comment]
@mimicria, завел тикет #130. Примеры запуска и выходной директории очень бы пригодились. По идее Honggfuzz выглядит похоже на libFuzzer. Так что после вынесения общих функций во время рефакторинга casr-libfuzzer и casr-afl должно несложно делаться.

**Comment by PaDarochek** [comment]
@keller05 Support for crash triaging via casr-libfuzzer for both Jazzer.js and jsfuzz has just been added to CASR

**Comment by anfedotoff** [comment]
We currently have no plans to support syzkaller.
