### ISSUE TITLE
odr-violation parsing error

### ISSUE THREAD

**Issue by sunforgb** [ispras/casr#123]
Hello! 
When using the CASR I ran into the problem that a report based on the sanitizer output isn't generated, if the error class is odr-violation. Instead the report is generated based on the casr-gdb. The reason seems to be that regex being used for the SUMMARY string parsing, which also takes ":" into account:
libcasr/src/asan.rs:176:
```
SUMMARY: *(AddressSanitizer|libFuzzer): (\S+)
```
In this case, if the line "odr-violation:" specified in the SUMMARY, then the check in  libcasr/src/execution_class.rs:139 fails. Possible solution: 
```
SUMMARY: *(AddressSanitizer|libFuzzer): ([\w \-\(\)\_]+)
```
Or check for string matches not entirely. 

Attached the screenshot with a part of the problematic SUMMARY-line
![casr-error](https://github.com/ispras/casr/assets/79010861/511c0ea6-a7eb-40fc-bc44-0a5a3164e7e6)

![casr_execution_class](https://github.com/ispras/casr/assets/79010861/e865e65b-bd60-4895-8389-1a09efc27cac)

![casr_regex_asanrs](https://github.com/ispras/casr/assets/79010861/536819b9-5c44-4c7a-8d83-8f9be7250607)

**Comment by SweetVishnya** [comment]
Can you also provide sanitizer message for easier debugging? Or just SUMMARY message? You may anonymize it if you wish. However, please, save the exact format.

**Comment by SweetVishnya** [comment]
@sunforgb, can you, please, verify that `casr-san` built from branch `san-name-fix` (PR #125) works fine with your case?

**Comment by sunforgb** [comment]
@SweetVishnya  Sanitizer report:
```
=================================================================
==5826==ERROR: AddressSanitizer: odr-violation (0x00000031e7c0):
  [1] size=772 'mswitch_cfg' /sample-project/sample-lib/mswitch.c:19:11
  [2] size=772 'mswitch_cfg' /sample-project/sample-lib/mswitch.c:19:11
These globals were registered at these points:
  [1]:
    #0 0x2698bd in __asan_register_globals (/out/ASAN/sample_bin+0x2698bd)
    #1 0x70db66365389 in call_init /opt/build/glibc-2.28/elf/dl-init.c:72:3

  [2]:
    #0 0x2698bd in __asan_register_globals (/out/ASAN/sample_bin+0x2698bd)
    #1 0x309444 in __libc_csu_init (/out/ASAN/sample_bin+0x309444)

==5826==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'mswitch_cfg' at /sample-project/sample-lib/mswitch.c:19:11
==5826==ABORTING
```
`san-name-fix` works fine in my case

**Comment by SweetVishnya** [comment]
@sunforgb, it's great that fix works for you! We'll merge it after some code review.
