### ISSUE TITLE
Casr-ubsan report naming

### ISSUE THREAD

**Issue by sunforgb** [ispras/casr#200]
In the `casr-ubsan` utility, report names are generated based on the directory name, crash name, and crash line. However, `casr-san`, `casr-python`, and others generate report names only based on the crash name. Is it possible to unify the report naming so that it differs minimally from the crash name? For example, for `casr-ubsan`, could we generate reports similarly to `casr-san` (adding only the .casrper extension), or could we add the same low-level utility as `casr-san` (processing only one file without crash triage)?

**Comment by sunforgb** [comment]
So that is not possible to specify the "crash line" in the name of input like in the name of the generated report when copying the source input in save_report function of casr-ubsan.rs?

**Comment by SweetVishnya** [comment]
> So that is not possible to specify the "crash line" in the name of input like in the name of the generated report when copying the source input in save_report function of casr-ubsan.rs?

Yes, you're right.

**Comment by sunforgb** [comment]
But if I specify for UBSAN_OPTIONS `abort_on_error=1`, I suppose that I will not get multiple UBSAN warnings. Can this case be checked while generation of names?

**Comment by SweetVishnya** [comment]
In this case you may just try using casr-san

**Comment by SweetVishnya** [comment]
If you have a crash, you can use regular tooling like casr-san/casr-libfuzzer/casr-afl

**Comment by sunforgb** [comment]
If I use `casr-san` then report will be generated with `casr-gdb`, that is different from `casr-ubsan`. Example stacktrace:
```shell
/source/utils/source.c:1453:42: runtime error: left shift of negative value -1
    #0 0x618cc23c3595 in sample_func_1 /source/utils/source.c:1453:42
    #1 0x618cc23c3595 in sample_func_2 /source/utils/source.c:1206:21
    #2 0x618cc23bd8d0 in sample_func_3 /source/utils/source.c:1342:9
    #3 0x618cc23bd8d0 in main1 /source/utils/source.c:805:3
    #4 0x618cc23b95a7 in main /source/utils/source-harness.c:10:5
    #5 0x7f952688209a in __libc_start_main /opt/build/glibc-2.28/csu/../csu/libc-start.c:308:16
    #6 0x618cc238c679 in _start (/out/UBSAN/source-harness+0x3a679) (BuildId: e094782c7468313a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /source/utils/source.c:1453:42 in 
Аварийный останов (стек памяти сброшен на диск)
```

**Comment by hkctkuy** [comment]
> But if I specify for UBSAN_OPTIONS `abort_on_error=1`, I suppose that I will not get multiple UBSAN warnings. Can this case be checked while generation of names?

It seems not a good idea to use `abort_on_error=1`. Maybe you can explain your use case in more detail?

**Comment by sunforgb** [comment]
I'm using AFLplusplus in fuzzing purposes, including CI/CD. For now, I'm trying to add fuzzing with UBSAN to my pipelines (with ASAN it works fine). AFL team hardcoded compile option -fsanitize-undefined-trap-on-error, so i disable it. Target with AFL_USE_UBSAN, and UBSAN_OPTIONS=abort_on_error=1,print_stacktrace=true, gives me UBSAN crashes, so in this case I'm fine. But then I want to create  reports from this crashes and provide some regression testing with old found crashes. In this case, I use casr-san for ASAN and LSAN crashes, and I can easily compare crash and it's report to send information to backend. For casr-ubsan report name and crash name are different not only by extension but also with crash line, so I'm just trying to understand, if there is a way to use my automation  for it.
So, I need to use abort_on_error=1, because otherwise AFLplusplus do not recognize inputs as UndefinedBehavior crashes.

**Comment by anfedotoff** [comment]
> I'm using AFLplusplus in fuzzing purposes, including CI/CD. For now, I'm trying to add fuzzing with UBSAN to my pipelines (with ASAN it works fine). AFL team hardcoded compile option -fsanitize-undefined-trap-on-error, so i disable it. Target with AFL_USE_UBSAN, and UBSAN_OPTIONS=abort_on_error=1,print_stacktrace=true, gives me UBSAN crashes, so in this case I'm fine. But then I want to create reports from this crashes and provide some regression testing with old found crashes. In this case, I use casr-san for ASAN and LSAN crashes, and I can easily compare crash and it's report to send information to backend. For casr-ubsan report name and crash name are different not only by extension but also with crash line, so I'm just trying to understand, if there is a way to use my automation for it. So, I need to use abort_on_error=1, because otherwise AFLplusplus do not recognize inputs as UndefinedBehavior crashes.

I recommend you not to use `abort_on_error=1`, because in some cases ubsan warnings could happen during fuzzing startup, before processing any data from fuzzer. Try to use this pipeline:

1. Do fuzzing for some amount of time. 
2. Minimize corpus. It's necessary if you do fuzzing on multiple cores. 
3. Run casr-ubsan on minimized corpus.

**Comment by sunforgb** [comment]
We will try this approach, thank you. But we also need to catch the termination of the target program at the start, since when using the ISP RAS SAFEC compiler at the Safe1 level, the program terminates when the UndefinedBehaviorSanitizer is triggered without any output. I would also like the casr-san utility to handle UBSAN crashes, but maybe I need to open a separate issue for this?
