### ISSUE TITLE
Tests that use LD_PRELOAD hang on Ubuntu 22.04 GitHub runners

### ISSUE THREAD

**Issue by anfedotoff** [ispras/casr#208]
It seems, that `test_casr_js_native_jsfuzz`  hangs in loop. CI is broken, @PaDarochek, please, have a look.

**Comment by SweetVishnya** [comment]
Actually, `test_casr_libfuzzer_jazzer_js_xml2js` test is hanging.

**Comment by SweetVishnya** [comment]
Actually, test_casr_java is failing.

**Comment by SweetVishnya** [comment]
casr-java call hangs on LD_PRELOAD [here](https://github.com/ispras/casr/blob/da980b3f6f445890a95304e4650f89d2f80dd2bb/casr/tests/tests.rs#L4262)

**Comment by SweetVishnya** [comment]
We may temporary use Ubuntu 20.04 in our CI (#211). Then we should examine why tests using LD_PRELOAD hang on Ubuntu 22.04 GitHub runner.

**Comment by SweetVishnya** [comment]
In #215 I decided to run hanging tests on Ubuntu 20.04 in coverage workflow
