### ISSUE TITLE
[casr-gdb] Выводить значения регистров в шестнадцатеричной системе счисления

### ISSUE THREAD

**Issue by fe7ch** [ispras/casr#217]
Хотелось бы видеть значения регистров в шестнадцатеричной системе счисления, по аналогии с отладчиками, эмуляторами и тд.

В данный момент значения выводятся в десятичной системе и сопоставлять их визуально с остальной информацией из отчета затруднительно. 

Пример отчета:

```
"Registers": {
    "eax": 1279370224,
    "k2": 0,
    "k4": 0,
    "gs": 99,
    "ecx": 40754,
    "ebp": 4290934980,
    "ds": 43,
    "es": 43,
    "k0": 0,
    "fs": 0,
    "k3": 0,
    "k5": 0,
    "k6": 0,
    "esi": 7909726,
    "eflags": 2163202,
    "k1": 0,
    "ss": 43,
    "cs": 35,
    "esp": 4290934944,
    "ebx": 3809016,
    "eip": 284754,
    "k7": 0,
    "edx": 2750435135,
    "edi": 10735616
  },
  ```

**Comment by SweetVishnya** [comment]
Можно использовать casr-cli для отображения отчета, там числа шестнадцетиричные
