### ISSUE TITLE
Unable to use casr-dojo with CA certificates

### ISSUE THREAD

**Issue by tumanovm** [ispras/casr#225]
Hello!

I've tried to use `casr-dojo` to upload reports to self-hosted DefectDojo instance and stumbled upon the error below.

```
[INFO] Getting product id for <***>
[INFO] Trying to find existing product
[DEBUG] (1) reqwest::connect: starting new connection: https://defectdojo.<***>/
[DEBUG] (1) rustls::client::hs: No cached session for DnsName("defectdojo.<***>")
[DEBUG] (1) rustls::client::hs: Not resuming any session
[DEBUG] (1) rustls::client::hs: Using ciphersuite TLS13_AES_256_GCM_SHA384
[DEBUG] (1) rustls::client::tls13: Not resuming
[DEBUG] (1) rustls::client::tls13: TLS1.3 encrypted extensions: [ServerNameAck, Protocols([ProtocolName(687474702f312e31)])]
[DEBUG] (1) rustls::client::hs: ALPN protocol is Some(b"http/1.1")
Error: error sending request for url (https://defectdojo.<***>/api/v2/products/?name_exact=<***>)

Caused by:
    0: client error (Connect)
    1: invalid peer certificate: UnknownIssuer
```

To communicate with DD I've installed CA certificates by copying `.crt` file to `/usr/local/share/ca-certificates` and running `update-ca-certificates`. I am also able to use DD API using the same token that I am passing to `casr-dojo` using just `curl`. 

I made a little investigation and found out that `rustls`, which is used as [a TLS backend of reqwest crate](https://docs.rs/reqwest/latest/reqwest/tls/index.html) that you use for networking in `casr-dojo`, [does not and will not use CA certificates](https://docs.rs/craftls/latest/rustls/#non-features). Unfortunately I'm not good with both TLS and rust so I can't be sure, but it seems like there's no way for me as a client to configure my environment for `casr-dojo` to work. 

During investigation I was able to make a request when I built `reqwest::Client` and added certificates manually using [reqwest::ClientBuilder::add_root_certificate](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.add_root_certificate) or just switching to `reqwest`'s [native-tls feature](https://docs.rs/reqwest/latest/reqwest/tls/index.html#native-tls). There's also a crate called [rustls-native-certs](https://github.com/rustls/rustls-native-certs) which seems to solve exactly my type of problem (I haven't tested it yet) and is probably worth looking into.

Is it possible to add CA certificates support in `casr-dojo`?

Hope to hear from you and thanks for making this project. :)

**Comment by SweetVishnya** [comment]
Hi!

Yeah, I meaningly chose rustls as reqwest backend, although, knowing that it does not support custom CA. Using rustls allowed us to reduce dependency tree, not dynamically linking with openssl library, and support risc architectures. So, the best solution for your specific case is to recompile from source and [change](https://github.com/ispras/casr/blob/096555415c7b412b8b0baaeb6603a9b3bf2f0ca8/casr/Cargo.toml#L35) reqwest backend to native-tls.

**Comment by tumanovm** [comment]
> to recompile from source and [change](https://github.com/ispras/casr/blob/096555415c7b412b8b0baaeb6603a9b3bf2f0ca8/casr/Cargo.toml#L35) reqwest backend

That was the fallback approach that I've kept in mind, yes. Thank you for replying, I guess I'll stick with this plan

**Comment by SweetVishnya** [comment]
> > to recompile from source and [change](https://github.com/ispras/casr/blob/096555415c7b412b8b0baaeb6603a9b3bf2f0ca8/casr/Cargo.toml#L35) reqwest backend
> 
> That was the fallback approach that I've kept in mind, yes. Thank you for replying, I guess I'll stick with this plan

Please, let me know when you succeed or if you have any problems.

**Comment by tumanovm** [comment]
Changing `rustls-tls` `reqwest` feature to `native-tls` and then building binaries with `cargo build --release -F dojo` resolved certificate issues. Thanks! Please let me know if you will address this in the future so I could get rid of fork and just consume your package in some type of way.
