### ISSUE TITLE
Запрос на опцию casr-afl

### ISSUE THREAD

**Issue by mimicria** [ispras/casr#70]
День добрый!
Добавьте пожалуйста возможность через опцию командной строки задавать цель, отличную от считанной из конфигурации afl (чисто собранную без инструментации).

**Comment by SweetVishnya** [comment]
Опция в мастере.

**Comment by SweetVishnya** [comment]
> @SweetVishnya Коллеги, обнаружилась непонятная особенность, если собранного с инструментацией afl бинаря уже нет, но явно указан чисто собранный через -- , то опция игнорируется с ошибкой [ERROR] Couldn't read fuzz target binary: ... При этом замена в файле cmdline на чисто собранный помогает, но мне кажется это немного некорректным.

Это ожидаемое поведение, т.к. опция позволяет проверить, есть сохраняются ли креши на бинаре без санитайзеров. Кластеризация производится на основе запуска на оригинальном бинаре AFL.
