### ISSUE TITLE
casr-afl is unaware of out/default/crashes.DATE directories

### ISSUE THREAD

**Issue by vanhauser-thc** [ispras/casr#85]
when using casr-afl on an output directory that has restarts in it, it does not find saved crashes directories.
```
 $ ls out3/default/
cmdline                      fuzz_bitmap   hangs.2023-05-11-08:13:06
crashes                      fuzzer_setup  hangs.2023-06-07-10:04:14
crashes.2023-05-11-08:13:06  fuzzer_stats  plot_data
```
casr-afl needs not only to browse `crashes/` but check all `crashes*/` directories.

**Comment by SweetVishnya** [comment]
Nice catch! I'll fix it.

**Comment by vanhauser-thc** [comment]
btw is there a workaround for this:
`[ERROR] Error: Out of memory: hard_rss_limit_mb exhausted for input: ...`
?

**Comment by SweetVishnya** [comment]
> btw is there a workaround for this: `[ERROR] Error: Out of memory: hard_rss_limit_mb exhausted for input: ...` ?

`casr-san` [sets](https://github.com/ispras/casr/blob/master/casr/src/bin/casr-san.rs#L107) hard_rss_limit_mb to 2048 by default. You can override this by setting `ASAN_OPTIONS=hard_rss_limit_mb=0`.

**Comment by SweetVishnya** [comment]
> when using casr-afl on an output directory that has restarts in it, it does not find saved crashes directories.
> 
> ```
>  $ ls out3/default/
> cmdline                      fuzz_bitmap   hangs.2023-05-11-08:13:06
> crashes                      fuzzer_setup  hangs.2023-06-07-10:04:14
> crashes.2023-05-11-08:13:06  fuzzer_stats  plot_data
> ```
> 
> casr-afl needs not only to browse `crashes/` but check all `crashes*/` directories.

The fix is now in `master` branch.
